### ISSUE TITLE
Adjusting page scroll offset on collapse

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/o-expander#27]
On [next.ft.com/fastft](https://next.ft.com/fastft) there's a trick to make it feel less confusing/jumpy when you collapse one of the stories. When you click "Show less", the pageY scroll position is adjusted so that the button you clicked seems to remain in exactly the same position before and after the tap. Without this, it feels bad on mobile (e.g. in the Brexit stream).

This is currently done in the React component [here](https://github.com/Financial-Times/next-stream-page/blob/9dacebe16a7cf2a57e17bbc0a726327944c4a316/shared/components/card-open-in-stream/inline-article/index.js#L108-L116). But I want to do it somewhere else that doesn't use clientside React. And I don't think this logic should be done in different ways in lots of different places.

Can we do this scroll-back-up-on-expand logic in o-expander itself?

Maybe by configuring it with `data-o-expander-fix-scroll` or something?

**Comment by callumlocke** [comment]
@AlbertoElias @alicebartlett do you have an opinion on this? Happy to PR if agreed

**Comment by AlbertoElias** [comment]
That sounds like a really good idea @callumlocke Sorry that I missed the issue!

**Comment by rowanmanning** [comment]
Going to close this. It's a nice idea, we'll maybe consider if we do some work on o-expander in future
