### ISSUE TITLE
Expand functionality to allow accordion

### ISSUE THREAD

**Issue by eddichen** [Financial-Times/o-expander#32]
seems like this module does 90% of what's needed for an accordion functionality (where in a group only one section can be expanded at a time). Could this module be expanded to allow this or written so that users can access the methods used in this module?

**Comment by alicebartlett** [comment]
Hi @eddichen, this is a good idea and would be a sensible enhancement to this module. If you'd like to make open a pull request for this we'd be happy to merge.

**Comment by rowanmanning** [comment]
We're probably not turning this into an accordion after this many years. We now have a [proposals board](https://github.com/Financial-Times/origami-proposals) which would be a good place for this suggestion if somebody wants an accordion still.
