### ISSUE TITLE
Improve variants demo

### ISSUE THREAD

**Issue by onishiweb** [Financial-Times/o-expander#35]
The demo is really long, containing various ways the module can be used which means there's only portions of the HTML that can be copied from the demo. It would be better if demos could be copied completely and provide a working solution without much configuration instead of having to pick the correct part of the HTML to copy.

The variants demo could be split into separate demos and detail what should and shouldn't be used in products. Different configurations of `o-expander` should be explained in the readme if not done so already.

**Comment by rowanmanning** [comment]
Done 👍
