### ISSUE TITLE
Second demo not working properly on IE11 (the *collapsing to height of content* demo)

### ISSUE THREAD

**Issue by keirog** [Financial-Times/o-expander#5]
It doesn't seem to detect the content height correctly.

**Comment by wheresrhys** [comment]
This looks like a bug in ie11. scrollHeight on elements that a) don't have an explicit height and b) don't overflow is 1px greater than clientHeight.

Also happening in ie10.

Not a catastrophic bug so will park for now

**Comment by wheresrhys** [comment]
reduced test case http://jsbin.com/buhorapeyo/6/edit

**Comment by spriggsha** [comment]
Related:  Firefox 39 on Windows 7 (not an issue on FF39 Mac).  The toggle button appears regardless of the width of the window.  On the same machine, Chrome responds correctly.

**Comment by notlee** [comment]
Close this issue as mostly as it's five years old 😬  But also the demo appears to work now in IE11 and we [expect an explicit height](https://github.com/Financial-Times/o-expander/blob/v5.0.3/README.md#height-expander) for the height based expander.
