### ISSUE TITLE
Button not displayed, due to --inactive modifier class

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/o-expander#51]
This page has recently lost its o-expander button at the bottom of the table: https://ig.ft.com/sites/france-election/polls/

It seems to be hidden because the `--inactive` modifier has been added to the container. I've no idea why this has just changed in the last couple of days; we haven't updated our o-expander dep. But anyway, what does `--inactive` mean? How can I get rid of it? I see it's something to do with `isRequired` but I'm struggling to figure it out. We are using the build service to get o-expander.

**Comment by rowanmanning** [comment]
This seems to be fine now
