### ISSUE TITLE
V5

### ISSUE THREAD

**Issue by gvonkoss** [Financial-Times/o-expander#68]
Turns out reading o-expander code is somewhat confusing, so it should be a candidate for a major. Perhaps it may be worth investigating the differences between this component and [`o-toggle`](https://github.com/Financial-Times/o-toggle) to see if we can combine them.

**Comment by notlee** [comment]
> Turns out reading o-expander code is somewhat confusing, so it should be a candidate for a major. 

Yes! We'll do this as part of the major cascade  https://github.com/Financial-Times/o-expander/pull/75

>Perhaps it may be worth investigating the differences between this component and o-toggle to see if we can combine them.

Good suggestion. I've created an issue to carry this forward: https://github.com/Financial-Times/o-toggle/issues/33
